projeto/config/routes.rb
Projeto::Application.routes.draw do
	resources :questaos do
		resources :escolhas
	end

	root :to => 'inicio#index'

end

projeto/app/models/escolha.rb
class Escolha < ActiveRecord::Base
  belongs_to :questao
  attr_accessible :texto, :voto
end

projeto/app/models/questao.rb
class Questao < ActiveRecord::Base
	attr_accessible :data,:texto,:respostas_attributes

	validates :data, :presence=>true
	validates :texto, :presence=>true, :length=>{:minimum=>5}

	has_many :escolhas, :dependent=>:destroy
	has_many :respostas

	accepts_nested_attributes_for :respostas, :allow_destroy=>:true,
		:reject_if=>proc {|attrs| attrs.all?{|k,v| v.blank?}}
end

projeto/app/models/resposta.rb
class Resposta < ActiveRecord::Base
  belongs_to :questao
  attr_accessible :texto
end

projeto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

projeto/app/controllers/escolhas_controller.rb
class EscolhasController < ApplicationController
	http_basic_authenticate_with :name=>'user', :password=>'pass', :only=>:destroy

	def create
		@questao = Questao.find(params[:questao_id])
		@escolha = @questao.escolhas.create(params[:escolha])

		redirect_to questao_path(@questao)
	end

	def destroy
		@questao = Questao.find(params[:questao_id])
		@escolha = @questao.escolhas.find(params[:id])
		@escolha.destroy
		redirect_to questao_path(@questao)
	end
end

projeto/app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

projeto/app/controllers/questaos_controller.rb
class QuestaosController < ApplicationController
  http_basic_authenticate_with :name=>'user', :password=>'pass', :except=>[:index,:show]
  
  # GET /questaos
  # GET /questaos.json
  def index
    @questaos = Questao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questaos }
    end
  end

  # GET /questaos/1
  # GET /questaos/1.json
  def show
    @questao = Questao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @questao }
    end
  end

  # GET /questaos/new
  # GET /questaos/new.json
  def new
    @questao = Questao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @questao }
    end
  end

  # GET /questaos/1/edit
  def edit
    @questao = Questao.find(params[:id])
  end

  # POST /questaos
  # POST /questaos.json
  def create
    @questao = Questao.new(params[:questao])

    respond_to do |format|
      if @questao.save
        format.html { redirect_to @questao, notice: 'Questao was successfully created.' }
        format.json { render json: @questao, status: :created, location: @questao }
      else
        format.html { render action: "new" }
        format.json { render json: @questao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questaos/1
  # PUT /questaos/1.json
  def update
    @questao = Questao.find(params[:id])

    respond_to do |format|
      if @questao.update_attributes(params[:questao])
        format.html { redirect_to @questao, notice: 'Questao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @questao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questaos/1
  # DELETE /questaos/1.json
  def destroy
    @questao = Questao.find(params[:id])
    @questao.destroy

    respond_to do |format|
      format.html { redirect_to questaos_url }
      format.json { head :no_content }
    end
  end
end

projeto/app/helpers/application_helper.rb
module ApplicationHelper
end

projeto/app/helpers/escolhas_helper.rb
module EscolhasHelper
end

projeto/app/helpers/inicio_helper.rb
module InicioHelper
end

projeto/app/helpers/questaos_helper.rb
module QuestaosHelper
	def join_respostas(questao)
		questao.respostas.map{|it| it.texto}.join(", ")
	end
end

projeto/app/views/escolhas/_escolha.html.erb
<p>
	<b>Texto:</b>
	<%= escolha.texto %>
</p>
<p>
	<b>Data:</b>
	<%= escolha.voto %>
</p>
<p>
	<%= link_to 'Remover Escolha', [escolha.questao, escolha],
		:confirm=>'Esta Seguro?', :method=>:delete %>
</p>

projeto/app/views/escolhas/_form.html.erb
<%= form_for([@questao, @questao.escolhas.build]) do |f| %>
	<div class="field">
		<%= f.label :texto %>
		<%= f.text_area :texto %>
	</div>
	<div class="field">
		<%= f.label :voto %>
		<%= f.text_field :voto %>
	</div>
	<div class="actions"> <%= f.submit %> </div>
<% end %>

projeto/app/views/inicio/index.html.erb
<h1>Inicio#index</h1>
<p>Find me in app/views/inicio/index.html.erb</p>
<%= link_to 'Questoes', questaos_path %>

projeto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projeto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background:#EDEDED;">

<%= yield %>

</body>
</html>

projeto/app/views/questaos/_form.html.erb
<% @questao.respostas.build %>

<%= form_for(@questao) do |qf| %>
  <% if @questao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questao.errors.count, "error") %> prohibited this questao from being saved:</h2>

      <ul>
      <% @questao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= qf.label :texto %><br />
    <%= qf.text_field :texto %>
  </div>
  <div class="field">
    <%= qf.label :data %><br />
    <%= qf.date_select :data %>
  </div>

  <h2>Respostas</h2>
  <%= render :partial=>'respostas/form', :locals=>{:form=>qf} %>

  <div class="actions">
    <%= qf.submit %>
  </div>
<% end %>

projeto/app/views/questaos/edit.html.erb
<h1>Editing questao</h1>

<%= render 'form' %>

<%= link_to 'Show', @questao %> |
<%= link_to 'Back', questaos_path %>

projeto/app/views/questaos/index.html.erb
<h1>Listing questaos</h1>

<table>
  <tr>
    <th>Texto</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questaos.each do |questao| %>
  <tr>
    <td><%= questao.texto %></td>
    <td><%= questao.data %></td>
    <td><%= link_to 'Show', questao %></td>
    <td><%= link_to 'Edit', edit_questao_path(questao) %></td>
    <td><%= link_to 'Destroy', questao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Questao', new_questao_path %>

projeto/app/views/questaos/new.html.erb
<h1>New questao</h1>

<%= render 'form' %>

<%= link_to 'Back', questaos_path %>

projeto/app/views/questaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Texto:</b>
  <%= @questao.texto %>
</p>

<p>
  <b>Data:</b>
  <%= @questao.data %>
</p>

<p>
	<b>Respostas:</b>
	<%= join_respostas(@questao) %>
</p>

<h2>Escolhas</h2>
<%= render @questao.escolhas %>

<h2>Insere Escolha:</h2>
<%= render 'escolhas/form' %>

<%= link_to 'Edit', edit_questao_path(@questao) %> |
<%= link_to 'Back', questaos_path %>

projeto/app/views/respostas/_form.html.erb
<%= form.fields_for :respostas do |rf| %>
	<div class="field">
		<%= rf.label :texto,'Texto:' %>
		<%= rf.text_field :texto %>
	</div>

	<% unless rf.object.nil? || rf.object.new_record? %>
		<div class="field">
			<%= rf.label :_destroy, 'Remove:' %>
			<%= rf.check_box :_destroy %>
		</div>
	<% end %>
<% end %>